### PR TITLE
cleanup: fix static assert on MacOS

### PR DESCRIPTION
**Pull request by barracuda156**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/toxic/358)

### CODE REVIEW

**Comment by JFreegman** [comment]
Looks good. You just need to give the commit a [canonical title](https://github.com/TokTok/toxic/pull/358/checks?check_run_id=21954247917), e.g. `cleanup: fix static assert on MacOS`

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/toxic/358)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained

**Comment by JFreegman** [comment]
> @JFreegman Sorry for a delay. Is it okay now?

Yep, just need to rebase it again, then it's ready to merge

**Comment by barracuda156** [comment]
> > @JFreegman Sorry for a delay. Is it okay now?
> 
> Yep, just need to rebase it again, then it's ready to merge

Rebased.

**Pull request merged**
