### PR TITLE
Make Toxic easier to port

### PR DESCRIPTION
**Pull request by mazocomp**
Support DragonFlyBSD, use sed(1) instead of rev(1) and cut(1), use variables via env(1) too.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/23)

### CODE REVIEW

**Comment by mazocomp** [comment]
@iphydf All In One :)

**Comment by iphydf** [comment]
Ok, can you give this a better title that is a 1-sentence description of what this does? (something something dragonfly)

**Comment by iphydf** [comment]
Also rebase on master.

**Comment by mazocomp** [comment]
(thinking...)

**Comment by mazocomp** [comment]
@JFreegman by doing tests I see that user should now provide CFLAGS and LDFLAGs only via env(1), I'm thinking how to deal with that

**Comment by mazocomp** [comment]
Hm, I have an idea, but I'll make cosmetic changes first.

**Comment by mazocomp** [comment]
@JFreegman @iphydf How about this? I hope this will make Toxic build at Solaris/illumos too (can't test that).

**Comment by JFreegman** [comment]
Is there a technical reason users of DragonFlyBSD can't supply their custom flags in the standard way using USER_* variables? If not, I don't think a makefile overhaul is warranted for a convenience feature that only applies to users of an unorthodox system. Especially considering that it can't easily be tested on all relevant platforms for breakage. Let's just get it building and running for now.

**Comment by mazocomp** [comment]
@JFreegman in *BSD world ports systems provide environment variables CFLAGS and LDFLAGS
I, maintainer, am responsible to make sure those defaults get passed to your Makefile, so I have to do:
```
MAKE_ARGS=       CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
```
Also as a maintainer I'm responsible to not make a debug build.

**Comment by mazocomp** [comment]
@JFreegman but that's not over, at 0.8.2 release's state I have to make a more ugly step:
```
MAKE_ARGS+=       PREFIX="${PREFIX}"
```

**Comment by mazocomp** [comment]
@JFreegman `export PREFIX=""` setups PREFIX env(1) variable to be permanent until you exit shell (not if you're using C shell, you have to use `setenv PREFIX ""`:
```
$ export PREFIX="/raven"
$ printenv PREFIX
/raven
```
That is, you choose a PREFIX via environment variable, not via make arg.

If you take a careful look, OSX includes "osx_video.h", not <sys/videoio.h> or <linux/videodev2.h>

**Comment by mazocomp** [comment]
@JFreegman *BSD ports systems provide PREFIX as an environment variable, there's no reason to provide it as an argument to make

**Comment by JFreegman** [comment]
> @JFreegman export PREFIX="" setups PREFIX env(1) variable to be permanent until you exit shell (not if you're using C shell, you have to use setenv PREFIX "":

I understand the intent. It doesn't work though. make ignores the PREFIX environment variable, at least on my debian-based system.

> If you take a careful look, OSX includes "osx_video.h", not <sys/videoio.h> or <linux/videodev2.h>

My mistake, those should be nested or commented or both (but not in this PR).

**Comment by mazocomp** [comment]
I wonder what's wrong with GNU make provided by Debian?

**Comment by mazocomp** [comment]
@JFreegman oh, wait, I get it now: your sudo config ignores environment variables.

**Comment by mazocomp** [comment]
@JFreegman you have to configure sudo to keep environment variables, awesome, isn't it?

**Comment by JFreegman** [comment]
> oh, wait, I get it now: your sudo config ignores environment variables.

I don't think that's the case because setting an environment variable for CFLAGS works as intended.

**Comment by mazocomp** [comment]
@JFreegman try running `make install` without sudo, you're installing it in your home directory anyway

**Comment by JFreegman** [comment]
> @JFreegman try running make install without sudo, you're installing it in your home directory anyway

Strangely enough that did work. We're going to have to mention that caveat somewhere since this is the default setting that most people are running.

**Comment by mazocomp** [comment]
@JFreegman I use doas instead of sudo, it's more secure and easier to configure :P
```
% cat /raven/etc/doas.conf
permit keepenv :wheel
% setenv PREFIX /home/mazocomp/temp
% doas printenv PREFIX
doas (mazocomp@mazocomp.lan) password: 
/home/mazocomp/temp
```

**Comment by mazocomp** [comment]
@JFreegman I've updated INSTALL.md, now it is:
```
make
sudo env PREFIX="/where/to/install" make install
```

**Comment by mazocomp** [comment]
but `sudo make PREFIX="/where/to/install"` is still legal

**Comment by nurupo** [comment]
Hm, interesting, [apparently env can by used like that too](https://linux.die.net/man/1/env). I remember setting up FreeBSD builds for c-toxcore and the regular `VAR=VAL command` not working in tcsh, so I had to use `env VAR=VAL command` instead, but I thought it was some tcsh-specific built-in function, not a standard program. Still, `VAR=VAL command` is more common in bash, though I'm not sure if I should really block the PR on that since both ways are valid.

**Comment by nurupo** [comment]
There, retracted.

**Comment by avoidr** [comment]
```
- echo $$f | sed "s/.*\.//"
+ echo ${f##*.}
```

Even shorter, and part of POSIX, if I am not mistaken.

**Comment by mazocomp** [comment]
@avoidr wow, that's so inconvenient, Vim's syntax highlighting thinks that's a comment.

**Comment by mazocomp** [comment]
@avoidr 
```
Installing man pages
/bin/sh: f##*.: not found
/bin/sh: f##*.: not found
```

**Comment by avoidr** [comment]
I don't know, it works in straight shell: `f=toxic.conf.5; echo ${f##*.}`

I did not test it in a Makefile, I was just saying anyway.

>Vim's syntax highlighting thinks that's a comment.

Then that's a bug.

**Comment by mazocomp** [comment]
@avoidr oh, that's a stupid font in github, I didn't notice curly braces.

**Comment by mazocomp** [comment]
Are you all waiting for me to sign the CLA?

**Comment by iphydf** [comment]
No, but can you sign your commits and rebase on master? If you can't sign your commits, I can do that for you. Let me know.

**Comment by mazocomp** [comment]
@iphydf why sign commits and why rebase the fork?

**Comment by mazocomp** [comment]
(note that GPG tool is not available to me)

**Comment by iphydf** [comment]
Rebasing on master avoids a merge commit. It's a bit wasteful to have 50% of the PR be merge commits. I've done it on your behalf, so nothing left to do. I'll merge once CI has run.

**Comment by mazocomp** [comment]
@iphydf PRs are wasteful, it's better to send a patch file directly, just run `patch -i path/to/patch/file` and `git commit`

**Pull request merged**
