### PR TITLE
feat: Add ability to skip words in input field with ctrl-left/right arrow

### PR DESCRIPTION
**Pull request by JFreegman**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/89)

### CODE REVIEW

**Comment by nurupo** [comment]
Re-built toxic with newest changes. Ctrl+Arrows still do nothing.

In addition, Ctrl+P is now broken. When I press Ctrl+P nothing happens. However, when I press Ctrl+P followed by any key, then the original Ctrl-P functionality gets triggered.

Surprisingly, Ctrl+O works fine.

**Comment by JFreegman** [comment]
> Re-built toxic with newest changes. Ctrl+Arrows still do nothing.
> 
> In addition, Ctrl+P is now broken. When I press Ctrl+P nothing happens. However, when I press Ctrl+P followed by any key, then the original Ctrl+P functionality gets triggered.
> 
> Surprisingly, Ctrl+O works fine.

That's strange, I guess the hack I wrote for manual key sequence detection isn't portable. So much for that idea. I think we're just going to have to live with it not working on some systems

**Comment by nurupo** [comment]
>Could you double check that you have the latest commit and recompiled?

```
commit e428879bebb964a0435414ce00add7ffb2253ade (HEAD -> JFreegman-word-skip)
```

Tested it outside docker.

Ctrl+P works properly when run outside of docker.

Ctrl+arrows still don't work for me, tested in konsole, xterm and tty, all outside of docker.

Well, it doesn't seem like that PR breaks anything as far as I can tell, so I don't see any downsides to merging it.

**Review by nurupo — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/89)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
