### PR TITLE
feat: Merge new groupchat support

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/228)

### CODE REVIEW

**Review by iphydf — CHANGES_REQUESTED** [review]
Can you have a look at the static analysis failures. Are they all false positives?

**Comment by JFreegman** [comment]
> Can you have a look at the static analysis failures. Are they all false positives?

The Codacy ones are all code complexity warnings and the Codefactor ones are all false positives. Bazel config seems broken.

**Comment by iphydf** [comment]
This fixes the false positives. cppcheck doesn't know that `exit_*` functions don't return.

```
diff --git a/src/toxic.h b/src/toxic.h
index 1a1d097..eb57183 100644
--- a/src/toxic.h
+++ b/src/toxic.h
@@ -114,8 +114,8 @@ void flag_interface_refresh(void);
 /* Sets ncurses refresh rate. Lower values make it refresh more often. */
 void set_window_refresh_rate(size_t refresh_rate);

-void exit_toxic_success(Tox *m);
-void exit_toxic_err(const char *errmsg, int errcode);
+void exit_toxic_success(Tox *m) __attribute__((__noreturn__));
+void exit_toxic_err(const char *errmsg, int errcode) __attribute__((__noreturn__));

 int store_data(Tox *m, const char *path);

```

**Comment by iphydf** [comment]
```
script/build-minimal-static-toxic.sh#L160
This \- will be a regular '-' in this context. (SC1001)
```

Is this a false positive?

**Review by iphydf — APPROVED** [review]

**Comment by iphydf** [comment]
> ```
> script/build-minimal-static-toxic.sh#L160
> This \- will be a regular '-' in this context. (SC1001)
> ```
> 
> Is this a false positive?

Looks like no, that's a true positive (though not really important, it's just a bit ugly). Fix and merge?

**Review by iphydf — APPROVED** [review]

**Pull request merged**
