### PR TITLE
Add config option for the notification timeout duration

### PR DESCRIPTION
**Pull request by kitsunenokenja**
Re-created PR per maintainer's request.

This change enhances the default setting of 3000 milliseconds for the notification timeout by making the value a user config option.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/38)

### CODE REVIEW

**Comment by JFreegman** [comment]
@kitsunenokenja You'll need to sign your commit before it can be merged.

**Comment by kitsunenokenja** [comment]
If this last update didn't work I'll revisit later to work out the settings for GPG signing.

**Comment by JFreegman** [comment]
We still can't merge because you haven't uploaded your public key to github in order to verify your signatures.  I know it's annoying, but you only have to set it up once.

**Comment by kitsunenokenja** [comment]
I already use GPG signing with the Gentoo project here on GitHub. Now I need to sort out the config for working with `-S` it on another repo. I'll amend again as soon as I can.

**Comment by kitsunenokenja** [comment]
@JFreegman, sorry for the delay! I believe this is ready now.

**Pull request merged**
