### PR TITLE
Add input line text to history on UP and DOWN keys

### PR DESCRIPTION
**Pull request by expert975**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/46)

### CODE REVIEW

**Comment by JFreegman** [comment]
The commit needs to be signed before merging

**Comment by expert975** [comment]
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFyxXB4BEAC9a0zjVdlyixi6ZWArztjN1f5GJ5vAHDXLBIY8cDa+oH8r1D+P
yT4OfKEJV/tGJTfArYmwW6PY0LYvQTN8ChgsM7W05Laa6aH3Ed5cwxlFwXzUCE4X
XBrgxUhp6XdHIWYKiyhODen3sPXaEX8wtogamB4yy4yj5+xGkKq2XX907k4a5Q/Q
+PY/9Zfc9XRAnlYnmc/Y+ItgRfX+CQ7eiejXl7VPm++v9EoMwy+yrCcyhRStFrL/
MarI3/hwBM6+cXOVIqfn+M1Oyuery4I5pI15r1MHfGM0in3Ayi16Ywm9hUow8INN
mt5sYnvOExZr7+p090nwBhxYcdRYrzdz3ghobuXZcb5L/eY1T7SNX7NZ3NeNn02l
BGjFkvQTBxXBxPyqixZ94ROeDY49Q+ikB13PoiXjd6ur5uVSZcYrh0fBPnz48pq9
eB6mFT/wSbFjCOkxRU85Vd8wKcRSQIw6bUXHQsoXBRReTWmR+sXcFMmM03v+U/kL
H4CElftc9gbQGe5rGLM6oO+CLI9lel0bLtttYQ+0gY1Yz0DfjAlrYa9c3Fow04YN
0VwLAckoPsgQT3z4pMyNAw+MMGQByw4JZJktDzSjwrZXY4Tr5U5j99TyXWfGHZvD
3oGYW7UQ0xe4rnf6mLmXaoRdi3jzYUIqNAWVcWwWrHJSKH82w+QnltLnDwARAQAB
tCxSb2RyaWdvIDxyb2RyaWdvY29tcHV0YWRvcmVzMTI1QGhvdG1haWwuY29tPokC
VAQTAQgAPhYhBBMTpamqCkKglhX6NW7Qnpmd0XM5BQJcsVweAhsjBQkJZgGABQsJ
CAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEG7Qnpmd0XM5DYMP/1WS4loINg//J+xN
EB/uyQ0yDoGErTAAPvWFJtkd1jsk6Sl1Z8OyLA3qCOZ9aaL/89CGyMsWSiIAuiXp
VxFjUcA00S5W2YjTtpS+lrU7gi8xCq+AaZ4hCg9yy0iu9reB2oFkJgNDj18QaDsp
ioWg5R0qM21zc3pI7FZ4xIx6vB4Zdt10t3p6oNdD6BEmXFtMkJLvO6o0pnRUc5D1
PEZMslnkG6CHS667UXGd7Ez1xp9t+ENa19nSxk1Dial62UV6Z+uSxXTdPRs8/pWy
2yMf3pMVw2Icu2Uf6s/MBJqzisZTLPDCYMBvNbSHSNbtf/n7lVHqbMf/kBjXjvEa
cdsR6abWEOseRwcOTl5YHsD0wrijkKHtWE2L7visYkGFXl8ajgGjv6f/iZQ4EYyp
wG/MgvCWriad+WQ7USX6XLgbpeMz5TeAL4S/Vyia5zOVRUINnZiP6IovLaNJtnTo
xPv4VIMeHa1p0yJ0xFZlcmvHCpggZLi1neYJoaq7iX+xtBcpqUiB+uiftIyvNY9r
9VSDPxwNA1W8+HFjWcjCpiwfSuZuylmaoAkYdOqN0ttKri9ogfKJUuecHONXtb+n
ffLFEb7S5ddrQpRF2/4FcVvgURXzeuz8jRofal5rsDd62qfj4CDd1ECc8d7ugkLO
vk4EQ5HwTLb5xvNzejNGY5vbHDJRuQINBFyxXB4BEAC5US0/ADVB5u/jiFaTaxYC
7OkD/tsqx+bh1qrHz6mSNxVLA1kH2cuz+7HIvVArw5uNHJhNBeYQ1t4VFoBB+PFa
iBErlfOE/3IStAdvC013rb1uq70NCFiwHpqjsan4qGQ6FnhGkt72/upJO0O6dpeh
bGAqRF88yDeqzrY6VfVoeAvZSfxwKynD30/JvB/IcQKfm4699vKclwMbcV+kBPo0
ymJHmaTpSRY2edt5Nqy0hoWwzLW+7189MyQBzfMJsqDJ71nyyBC0QC0yu7vPR5fu
+p9pG8uC+k7Y7iWGU9nhpabsQ5f//RLwPYtigD0RZmLPy6IuODO8sCSPolFpJtw0
WBip/8kZmY0a6rqufk9zjNRTJCbAexpcNeIk6ONY/NttGr6EDqDHpWPfuuDmz+eB
zNAfi6QvIYqHBKnfa1Jyv+2y0mYaFLfV4SEmCbQ+t2HmI5rODNqcWR/sPmnGg8j4
wsSZAASlr9VwrZAwoQ7S8iORMnsyc85dH+kAW+cj8PLwSY+TbXNjsGNrTS2zXLSj
No8Sn1c8G1XOCpq0+u7O/xCm+dWfzHKZWyE7C3G9n1ojw1xP9a4AkrEa6fEi+080
rzOgAepjM9Bdw5nLRfZkXGkY+3XKOo5UG1G4z/jCVfvFw1fjUAxM9xL3cepT6jeh
eySfo0eT5WIGQFFTJLbscwARAQABiQI8BBgBCAAmFiEEExOlqaoKQqCWFfo1btCe
mZ3RczkFAlyxXB4CGwwFCQlmAYAACgkQbtCemZ3Rczm9thAAguY0f1YzwK18Hmda
yth4zG4P/LFEuMJKQ+C6FbuXK5RCDpYSnNS4DwMCrEItMoOMDHj6yQ5X9k/tBNJE
KgoXs94gSTXmv24qk/GY39SW9N7fB8tB/H8gQkqukoRoTtu5emWDFt/6OgkOaGsf
FXyWWSl9snyRmEm4KNiZtwKxFdVI0gAselbbCoZuu7quueIZcFcVDLjMdlclsnkh
BqwPjNTI6rz9VWHBIE88NmtzxOvoTOxLqcDFP16hF5K3I9RsbWZAUlwrr2AS3d/t
6b3Tx2S1wboNlQpPkMo3AQ+qNLvX0Jrmo9WqwjvW7K08U6L5IjRBk+bWtFIGPENr
Ks8+Lvz5klfM5mcj+JA3MnHmecFz0qk7/7muQnWaB6SyWL0QizQMhy08FdT7pSsM
cguFWExPgKuik3y7wj19TOpjgMmFfQI8mylX87HIzDBmtNnjk3vtcOeXoZaVTyYZ
QokE6K+NYH285whCVFkQHJMogRydzORPUUwS/vuGG3hOicOOO3Z5TYCR2zwUkHS1
8coeLzprFGEd3RsogVDm+Qghl5UlMqTOTPFxM5WgPbxv5xwvmjLzO/px7RLHR3uB
zRId0cPsO4IOHrZ7Ywjm0AK6OecnCDnh0yBi9IoOf8RVK0PkDGLlTiKRNTLAymGe
hbtXoO9PIuArJzCZckoma+5S50Q=
=RVKR
-----END PGP PUBLIC KEY BLOCK-----

**Comment by JFreegman** [comment]
You need to sign the actual commit via git using a public key associated with your github account. `git commit -S -m "commit message"`

See: https://help.github.com/en/github/authenticating-to-github/signing-commits

**Comment by expert975** [comment]
That's what I've done

**Comment by JFreegman** [comment]
You need to add your public key to your github account. When you look at the commit it should show a green "verified" button.

**Comment by expert975** [comment]
Done

**Pull request merged**
