### PR TITLE
feat: Add game module

### PR DESCRIPTION
**Pull request by JFreegman**
This PR includes a game module with a public API, along with four games: Chess, Centipede, Conway's Game of Life, and an original variation of Snake

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/187)

### CODE REVIEW

**Review by GrayHatter — COMMENTED** [review]
> Reviewed 25 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/187)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[cfg/checks/check_features.mk, line 24 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeJDpA-U4Koao3zY5t:-MbeJDpA-U4Koao3zY5u:bk6gvcu) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/cfg/checks/check_features.mk#L24)):*
> ```Makefile
> 
> #check if we want to build with game support
> GAMES := $(shell if [ -z "$(DISABLE_GAMES)" ] || [ "$(DISABLE_GAMES)" = "0" ] ; then echo enabled ; else echo disabled ; fi)
> ```

Using the shell/env for build options? Gross...
___
*[src/chat.c, line 788 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbeb1yrDmbaRywsse5H:-Mbeb1ys3YMkAwBM4oJo:bg2diq) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L788)):*
> ```C
>     GameType type = data[1];
> 
>     if (!game_type_is_multiplayer(type)) {
> ```

this probably shouldn't exist... what's it trying to do?
___
*[src/chat.c, line 805 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbebUN-DVb_u-3y98V9:-MbebUN-DVb_u-3y98VA:b-lc5dul) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L805)):*
> ```C
>     Friends.list[friend_number].game_invite.pending = true;
> 
>     uint32_t data_length = length - GAME_PACKET_HEADER_SIZE;
> ```

unsigned rollover likely isn't what you want...
___
*[src/chat.c, line 817 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbebc0S9T5bq6Pzkrnv:-Mbebc0S9T5bq6Pzkrnw:bo0qw0p) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L817)):*
> ```C
>         }
> 
>         memcpy(buf, data + GAME_PACKET_HEADER_SIZE, data_length);
> ```

OOB read
___
*[src/execute.c, line 53 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeJRdW-080tDpDJg2e:-MbeJRdW-080tDpDJg2f:b-wsi44v) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/execute.c#L53)):*
> ```C
>     { "/conference", cmd_conference    },
> #ifdef GAMES
>     { "/game",      cmd_game          },
> ```

are you sure about these semantics? Seems like they could be confusing.
___
*[src/friendlist.h, line 51 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeKI1SA-uzEsD7UUiq:-MbeKI1SA-uzEsD7UUir:btm3v27) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/friendlist.h#L51)):*
> ```objc
> #ifdef GAMES
> 
> struct GameInvite {
> ```

this doesn't belong here :/
___
*[src/friendlist.c, line 592 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeMBQP-VZrJFoWvPSI:-MbeMBQQCX7hGfa_5lCE:bkx4f5k) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/friendlist.c#L592)):*
> ```C
> static void friendlist_onGameInvite(ToxWindow *self, Tox *m, uint32_t friend_number, const uint8_t *data, size_t length)
> {
>     UNUSED_VAR(self);
> ```

are macros better than `(void)self;`?
___
*[src/game_chess.h, line 4 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeNHzqDckF5HMiTkGp:-MbeNHzqDckF5HMiTkGq:b-p6j7da) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_chess.h#L4)):*
> ```objc
>  *
>  *
>  *  Copyright (C) 2020 Toxic All Rights Reserved.
> ```

yes fuck up every file with nonsense... this totally needs to be in every file, not just the repo...
___
*[src/game_util.h, line 90 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeNxmaEX27JsEMalJU:-MbeNxmaEX27JsEMalJV:b-9to950) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.h#L90)):*
> ```objc
>  * Returns a random colour.
>  */
> int game_util_random_colour(void);
> ```

ahh, a Frenchy I see... :P

util files are almost always a mistake... perhaps `game_2dnav.c` instead?
___
*[src/game_util.c, line 112 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeZjFW7qAX09_YVu0-:-MbeZjFW7qAX09_YVu00:b-oa8ssy) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L112)):*
> ```C
> 
>         case SOUTH: {
>             ++(coords->y);
> ```

signed rollover, fix or comment?
___
*[src/game_util.c, line 163 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeO_Ql6dSOlJRA_QrV:-MbeO_Ql6dSOlJRA_QrW:b-l0l8ro) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L163)):*
> ```C
> static size_t net_pack_u16(uint8_t *bytes, uint16_t v)
> {
>     bytes[0] = (v >> 8) & 0xff;
> ```

fuck big endian systems I guess?
___
*[src/game_util.c, line 176 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeOy-hAdi0QWzdtE75:-MbeOy-hAdi0QWzdtE76:b-sk0x7a) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L176)):*
> ```C
> }
> 
> size_t game_util_pack_u32(uint8_t *bytes, uint32_t v)
> ```

this all appears needlessly complex
___
*[src/windows.h, line 48 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_87w6X2xUA3bNfwo:-Mbe_87w6X2xUA3bNfwp:b3ryiml) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.h#L48)):*
> ```objc
> 
> typedef enum CustomPacket {
>     CUSTOM_PACKET_GAME_INVITE = 160,
> ```

no protocol negotiation 
___
*[src/windows.h, line 313 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_HB53lZEwfV3CPxy:-Mbe_HB53lZEwfV3CPxz:bb7hquh) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.h#L313)):*
> ```objc
> void refresh_inactive_windows(void);
> 
> #endif // WINWDOWS_H
> ```

huh?
___
*[src/windows.c, line 902 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_dd39d2X1HJTdI6K:-Mbe_dd39d2X1HJTdI6L:b5pd8ti) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.c#L902)):*
> ```C
> 
> #ifdef GAMES
>         else if (w->type == WINDOW_TYPE_GAME) {
> ```

switch?

**Review by GrayHatter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/187)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[src/chat.c, line 818 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbeen2K1ZVHoATgyiJs:-Mbeen2K1ZVHoATgyiJt:b-niy616) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L818)):*
> ```C
> 
>         memcpy(buf, data + GAME_PACKET_HEADER_SIZE, data_length);
>         Friends.list[friend_number].game_invite.data = buf;
> ```

this doesn't even appear to be used anywhere... is it?

**Review by GrayHatter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/187)* status: 0 of 1 approvals obtained (waiting on @JFreegman)

___
*[src/chat.c, line 809 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbegTKY2PwabcD7jPHb:-MbegTKY2PwabcD7jPHc:b-dkmrrv) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L809)):*
> ```C
> 
>     if (data_length > 0) {
>         free(Friends.list[friend_number].game_invite.data);
> ```

friend controlled free here with ...
___
*[src/chat_commands.c, line 201 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbegXZGAXVWM2veEFWb:-MbegXZGAXVWM2veEFWc:b3ge8sl) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat_commands.c#L201)):*
> ```C
>     switch (ret) {
>         case 0: {
>             free(data);
> ```

user controlled free here.

is tox in a separate thread?

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/187)* status: 0 of 1 approvals obtained (waiting on @GrayHatter and @JFreegman)

___
*[cfg/checks/check_features.mk, line 24 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeJDpA-U4Koao3zY5t:-Mbg6rjN6NXWmjFMgHBW:bmdion3) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/cfg/checks/check_features.mk#L24)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

Using the shell/env for build options? Gross...
</blockquote></details>

Toxic's build system is gross in general but this isn't the place to fix it
___
*[src/chat.c, line 788 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbeb1yrDmbaRywsse5H:-Mbg7k8F2CvzpIKIgHIF:b1c4dxm) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L788)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this probably shouldn't exist... what's it trying to do?
</blockquote></details>

Without this check it would be possible for a friend to send you a single-player game request by manually modifying the packet. 
___
*[src/chat.c, line 805 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbebUN-DVb_u-3y98V9:-Mbg8a-s8k0bTPYL0m30:bp1siym) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L805)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

unsigned rollover likely isn't what you want...
</blockquote></details>

Line 774 checks that `length` is >= `GAME_PACKET_HEADER_SIZE`. However I should have a max length check somewhere in there too.
___
*[src/chat.c, line 817 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbebc0S9T5bq6Pzkrnv:-MbgBPgH2AE8T8uHqzCM:b-896fix) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L817)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

OOB read
</blockquote></details>

Done.
___
*[src/chat.c, line 818 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbeen2K1ZVHoATgyiJs:-MbgC88uEPVLtMYrLYmh:b-xzuu5) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L818)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this doesn't even appear to be used anywhere... is it?
</blockquote></details>

It's used in chat_commands.c when you accept a game request. This data contains the beginning state for the new game.
___
*[src/execute.c, line 53 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeJRdW-080tDpDJg2e:-MbgCWjV5Iucl1eucHFM:b-w64379) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/execute.c#L53)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

are you sure about these semantics? Seems like they could be confusing.
</blockquote></details>

It's fine for now, maybe worth cleaning up another time.
___
*[src/friendlist.h, line 51 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeKI1SA-uzEsD7UUiq:-MbgCg2j-yOJNbZfy0Mv:b-r4hkwx) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/friendlist.h#L51)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this doesn't belong here :/
</blockquote></details>

It's a data structure that's associated with a friend. where else would it go?
___
*[src/friendlist.c, line 592 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeMBQP-VZrJFoWvPSI:-MbgCwq2CJckXDJGZ8OF:bxdhhp2) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/friendlist.c#L592)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

are macros better than `(void)self;`?
</blockquote></details>

I think so.  Not in the scope of this PR either way.
___
*[src/game_chess.h, line 4 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeNHzqDckF5HMiTkGp:-MbgET_M9x5JF1sT5DpS:b-k3j22z) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_chess.h#L4)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

yes fuck up every file with nonsense... this totally needs to be in every file, not just the repo...
</blockquote></details>

I think a brief outline pointing to the license would be better. Not in the scope of this PR though.
___
*[src/game_util.h, line 90 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeNxmaEX27JsEMalJU:-MbgEuDo130jrD9CtPAS:b-8d3hpa) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.h#L90)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

ahh, a Frenchy I see... :P

util files are almost always a mistake... perhaps `game_2dnav.c` instead?
</blockquote></details>

What's the significance?
___
*[src/game_util.c, line 112 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeZjFW7qAX09_YVu0-:-MbgF1Z39BRdw2_D5m4C:b59gfs8) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L112)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

signed rollover, fix or comment?
</blockquote></details>

If used correctly rollover should be impossible. But I suppose we can't expect things to be used correctly.
___
*[src/game_util.c, line 163 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeO_Ql6dSOlJRA_QrV:-MbgG7fs9LOrBAjL9AWU:b-7yv2fe) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L163)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

fuck big endian systems I guess?
</blockquote></details>

What?
___
*[src/game_util.c, line 176 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbeOy-hAdi0QWzdtE75:-MbgGFo54zncjZxWsSE2:b-rjo93y) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/game_util.c#L176)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

this all appears needlessly complex
</blockquote></details>

How can they be simplified?
___
*[src/windows.h, line 48 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_87w6X2xUA3bNfwo:-MbgHMqr8Mv4RSV3m5KE:bamb0xg) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.h#L48)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

no protocol negotiation 
</blockquote></details>

The invite packet is protocol negotiation.
___
*[src/windows.h, line 313 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_HB53lZEwfV3CPxy:-MbgHV5oAGTS8EB3VzDd:b-896fix) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.h#L313)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Done.
___
*[src/windows.c, line 902 at r1](https://reviewable.io/reviews/toktok/toxic/187#-Mbe_dd39d2X1HJTdI6K:-MbgI1pqAQjBxyUBTaed:b-896fix) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/windows.c#L902)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

switch?
</blockquote></details>

Done.

**Review by JFreegman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/toxic/187)* status: 0 of 1 approvals obtained (waiting on @GrayHatter)

___
*[src/chat.c, line 809 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbegTKY2PwabcD7jPHb:-MbgK6It5uRQmo40pzat:bs7wumb) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat.c#L809)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

friend controlled free here with ...
</blockquote></details>

Done.
___
*[src/chat_commands.c, line 201 at r1](https://reviewable.io/reviews/toktok/toxic/187#-MbegXZGAXVWM2veEFWb:-MbgK_Ig9z5JlyaqbPt6:b-6j6x33) ([raw file](https://github.com/toktok/toxic/blob/321f694bb89b801d828d0866d6b00930c35c5f44/src/chat_commands.c#L201)):*
<details><summary><i>Previously, GrayHatter (Gregory Mullen) wrote…</i></summary><blockquote>

user controlled free here.

is tox in a separate thread?
</blockquote></details>

Yes, tox callbacks are in a separate thread from user input.

**Pull request closed without merging**
