### PR TITLE
test: Add a fully static build with A/V support.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/toxic/258)

### CODE REVIEW

**Comment by nurupo** [comment]
Does the a/v and x11 integration actually work through a Docker image? What arguments you pass when running the container to make them work?

When I was making the static tarball (not a Docker container) build of toxic I had to disable a/v for some reason. I think OpenAL-Soft was detecting which audio libraries I have at build-time, enabling only the audio backends for those libraries (well, afterall it can't built other backends with missing headers and library symbols), and then also hardcoding paths to their so-names to `dlopen()` them at run-time, or something along these lines? Don't remember exactly. Well, whatever it was, the end result was that the resulting fully static binary wasn't portable across different distros.

**Comment by nurupo** [comment]
Hm, I see `ALSOFT_DLOPEN=OFF`, I wonder if that all it takes to get it to work. Would need to play with OpenAL-Soft again.

**Comment by iphydf** [comment]
I don't know if it works in docker. Probably you can volume-mount enough X11 stuff into it to make it work. I only tested that it works in the terminal and that it connects. I don't have a working X server to test with at the moment.

**Comment by iphydf** [comment]
Closing for inactivity and pushback.

**Comment by nurupo** [comment]
Eh? What pushback? If you have interpreted my comments as a pushback then you are very mistaken, this PR is welcome by me. I have only expressed my surprise at you getting this to work and me not knowing the `ALSOFT_DLOPEN=OFF` option before, wanting to play around with that option at my spare time (as it might enable us to have av enabled in the minimal static toxic build, which has nothing to do with PR, i.e. you are not blocked by me playing around with that option). It would be great if someone who is familiar with toxic and able to test the a/v features could review this PR.

**Comment by JFreegman** [comment]
> It would be great if someone who is familiar with toxic and able to test the a/v features could review this PR.

I tested it and the A/V didn't work. I'm not against it though, I think it'd be great to get it working and merged.

**Pull request closed without merging**
