### PR TITLE
fix: Fix autocomplete behaviour for paths with spaces

### PR DESCRIPTION
**Pull request by JFreegman**
This change is [Reviewable](https://reviewable.io/reviews/toktok/toxic/39)

### CODE REVIEW

**Comment by zugz** [comment]
> -    const char *s = strrchr(tmp, ' ');
> +    const char *s = strchr(tmp, ' ');

But shouldn't we be completing the last word? That's what the 
documentation on the function suggests, anyway.

Could you explain the intention of this PR? Is it really about naming 
paths containing spaces without using backslashes or quotes? That 
doesn't sound like a good idea, does it?

More generally, why not use libreadline?

**Comment by JFreegman** [comment]
> But shouldn't we be completing the last word? That's what the documentation on the function suggests, anyway.

The intent for paths is to list all matches of the current input string, or complete the path if only one file/match exists. strchr is used to split the input string from the command. I just noticed another bug while thinking this over and have force pushed a change.

> Could you explain the intention of this PR?

It's a fix for the bug reported in https://github.com/JFreegman/toxic/issues/522

**Comment by zugz** [comment]
OK. That fix helps. I still don't like not quoting the spaces, but 
I guess changing that is outside the scope of this PR. More generally, 
this is pretty hairy code, and using readline instead looks like a good 
idea to me... but I guess that's also out of scope.

Could you add a quick description in the function documentation about 
how it behaves when completing paths, i.e. that everything after the 
first space is treated as a single path?

**Comment by zugz** [comment]
* Sunday, 2019-02-17 at 14:44 -0800 - zugz <notifications@github.com>:

>using readline instead looks like a good idea to me...

On second thoughts, readline probably isn't a good fit, because we want 
to capture some keystrokes for changing windows etc, and the user might 
well have bound those keys to line editing functions (in their 
.inputrc). Oh well.

**Comment by JFreegman** [comment]
> Could you add a quick description in the function documentation about how it behaves when completing paths, i.e. that everything after the first space is treated as a single path?

I'm not sure what this is supposed to clarify. What alternative behaviour would you expect for path auto-completion?

**Comment by zugz** [comment]
* Sunday, 2019-02-17 at 17:45 -0800 - JFreegman <notifications@github.com>:

>> Could you add a quick description in the function documentation about how it behaves when completing paths, i.e. that everything after the first space is treated as a single path?
>
>I'm not sure what this is supposed to clarify. What alternative behaviour would you expect for path auto-completion?

I'd normally expect unquoted spaces to separate arguments, and the 
completion to be on the final argument treated as a path. Like 
tab-completing in a shell.

**Comment by JFreegman** [comment]
> I'd normally expect unquoted spaces to separate arguments, and the completion to be on the final argument treated as a path. Like tab-completing in a shell.

Toxic's tab completion works identically to most common shells that I'm aware of, which will automatically escape spaces. Moreover, there are no commands in toxic that rely on tab completion and take extra arguments, so the desired behaviour is implicit.

**Comment by zugz** [comment]
* Sunday, 2019-02-17 at 23:02 -0800 - JFreegman <notifications@github.com>:

>> I'd normally expect unquoted spaces to separate arguments, and the 
>> completion to be on the final argument treated as a path. Like 
>> tab-completing in a shell.
>
>Toxic's tab completion works identically to most common shells that I'm 
>aware of, which will automatically escape spaces.

But toxic's tab completion seems not to be escaping spaces. I mean, 
I would normally expect that if I have a file 'aoeu snth' in the current 
directory and I type '\avatar aoe<tab>' then it would be completed to 
'\avatar aoeu\ snth', but instead it's completed to '\avatar aoeu snth'. 
If I typed '\avatar aoeu snt<tab>', I would expect it to complete to 
files starting with 'snt' rather than with 'aoeu snt'.

I understand now that toxic assumes that any command which takes a path 
takes it as its only argument, so there's no need to escape spaces. But 
I still think it's worth a comment, because it contrasts with the 
behaviour (described in the comment at the head of the function) for 
completing non-path lines, where only the last word is completed. iiuc.

**Comment by JFreegman** [comment]
Why don't you make that into another issue/PR and so can get this bug fix cleared through.

**Review by zugz — APPROVED** [review]

**Pull request merged**
